version: "3.8"

services:
  app:
    build: .
    container_name: intelligenter
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: intelligenter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intelligenter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
