services:
  - type: web
    name: intelligenter
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: WHOIS_API_KEY
        sync: false
