services:
  - type: web
    name: intelligenter
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:YOUR_PASSWORD@ep-mute-sky-adufxl3p-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: VIRUSTOTAL_API_KEY
        value: "your_vt_key"
      - key: WHOIS_API_KEY
        value: "your_whois_key"
      - key: PORT
        value: "3000"
